services:
  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: cerebras-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cerebras-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/muninmail.db
      - REDIS_URL=redis://redis:6379/0
      - IMAP_SERVER=${IMAP_SERVER:-imap.gmail.com}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - DEBUG=${DEBUG:-True}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    volumes:
      - sqlite_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      sh -c "
        echo 'Creating data directory...' &&
        mkdir -p /app/data &&
        chmod 755 /app/data &&
        echo 'Creating database file...' &&
        touch /app/data/muninmail.db &&
        chmod 664 /app/data/muninmail.db &&
        echo 'Running database migrations...' &&
        uv run alembic -c alembic.ini upgrade head &&
        echo 'Starting FastAPI server...' &&
        uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Next.js Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cerebras-frontend
    ports:
      - "9002:9002"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - API_INTERNAL_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Celery Worker for background email processing
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cerebras-celery-worker
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/muninmail.db
      - REDIS_URL=redis://redis:6379/0
      - IMAP_SERVER=${IMAP_SERVER:-imap.gmail.com}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - DEBUG=${DEBUG:-True}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    volumes:
      - sqlite_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for backend to initialize database...' &&
        python -c 'import time; time.sleep(30)' &&
        echo 'Starting Celery worker...' &&
        uv run celery -A src.celery_app worker --loglevel=info --concurrency=2
      "

  # Celery Beat for scheduled tasks (optional)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cerebras-celery-beat
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/data/muninmail.db
      - REDIS_URL=redis://redis:6379/0
      - IMAP_SERVER=${IMAP_SERVER:-imap.gmail.com}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
      - DEBUG=${DEBUG:-True}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    volumes:
      - sqlite_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for backend to initialize database...' &&
        python -c 'import time; time.sleep(35)' &&
        echo 'Starting Celery beat scheduler...' &&
        uv run celery -A src.celery_app beat --loglevel=info
      "

  # Celery Flower for monitoring (optional)
  celery-flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cerebras-celery-flower
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for Redis to be ready...' &&
        python -c 'import time; time.sleep(10)' &&
        echo 'Starting Celery Flower...' &&
        uv run celery -A src.celery_app flower --host=0.0.0.0 --port=5555
      "

volumes:
  redis_data:
  sqlite_data:


networks:
  default:
    name: cerebras-network
