[project]
name = "cerebras-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.5",
    "smolagents[all]>=1.16.1",
    "uvicorn>=0.34.2",
]
